export const DISPLAY_ALERT = "SHOW_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";

export const REGISTER_USER_BEGIN = "REGISTER_USER_BEGIN";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";

export const LOGIN_USER_BEGIN = "LOGIN_USER_BEGIN";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";

export const SETUP_USER_BEGIN = "SETUP_USER_BEGIN";
export const SETUP_USER_SUCCESS = "SETUP_USER_SUCCESS";
export const SETUP_USER_ERROR = "SETUP_USER_ERROR";

export const UPDATE_USER_BEGIN = "UPDATE_USER_BEGIN";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";

export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";
export const LOGOUT_USER = "LOGOUT_USER";

export const HANDLE_CHANGE = "HANDLE_CHANGE";
export const CLEAR_VALUES = "CLEAR_VALUES";

export const CREATE_JOB_BEGIN = "CREATE_JOB_BEGIN";
export const CREATE_JOB_SUCCESS = "CREATE_JOB_SUCCESS";
export const CREATE_JOB_ERROR = "CREATE_JOB_ERROR";

export const GET_JOBS_BEGIN = "GET_JOBS_BEGIN";
export const GET_JOBS_SUCCESS = "GET_JOBS_SUCCESS";

export const SET_EDIT_JOB = "SET_EDIT_JOB";

export const DELETE_JOB_BEGIN = "DELETE_JOB_BEGIN";

export const EDIT_JOB_BEGIN = "EDIT_JOB_BEGIN";
export const EDIT_JOB_SUCCESS = "EDIT_JOB_SUCCESS";
export const EDIT_JOB_ERROR = "EDIT_JOB_ERROR";

export const SHOW_STATS_BEGIN = "SHOW_STATS_BEGIN";
export const SHOW_STATS_SUCCESS = "SHOW_STATS_SUCCESS";

export const CLEAR_FILTERS = "CLEAR_FILTERS";

export const CHANGE_PAGE = "CHANGE_PAGE";

export const CHANGEPASSWORD_USER_BEGIN = "CHANGEPASSWORD_USER_BEGIN";
export const CHANGEPASSWORD_USER_SUCCESS = "CHANGEPASSWORD_USER_SUCCESS";
export const CHANGEPASSWORD_USER_ERROR = "CHANGEPASSWORD_USER_ERROR";

export const CREATE_COMPANY_BEGIN = "CREATE_COMPANY_BEGIN";
export const CREATE_COMPANY_SUCCESS = "CREATE_COMPANY_SUCCESS";
export const CREATE_COMPANY_ERROR = "CREATE_COMPANY_ERROR";

export const GET_COMPANY_BEGIN = "GET_COMPANY_BEGIN";
export const GET_COMPANY_SUCCESS = "GET_COMPANY_SUCCESS";

export const DELETE_COMPANY_BEGIN = "DELETE_COMPANY_BEGIN";

export const SET_EDIT_COMPANY = "SET_EDIT_COMPANY";

export const EDIT_COMPANY_BEGIN = "EDIT_COMPANY_BEGIN";
export const EDIT_COMPANY_SUCCESS = "EDIT_COMPANY_SUCCESS";
export const EDIT_COMPANY_ERROR = "EDIT_COMPANY_ERROR";

export const APPLY_JOB_BEGIN = "APPLY_JOB_BEGIN";
export const APPLY_JOB_SUCCESS = "APPLY_JOB_SUCCESS";
export const APPLY_JOB_ERROR = "APPLY_JOB_ERROR";

export const SET_JOB_ID = "SET_JOB_ID";

export const GET_APPLICATIONS_BEGIN = "GET_APPLICATIONS_BEGIN";
export const GET_APPLICATIONS_SUCCESS = "GET_APPLICATIONS_SUCCESS";

export const GET_APPLICANTS_BEGIN = "GET_APPLICANTS_BEGIN";
export const GET_APPLICANTS_SUCCESS = "GET_APPLICANTS_SUCCESS";

export const DELETE_JOBAPPLICATION_BEGIN = "DELETE_JOBAPPLICATION_BEGIN";

export const GET_USERS_BEGIN = "GET_USERS_BEGIN";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";

export const DELETE_USER_BEGIN = "DELETE_USER_BEGIN";

export const UPDATE_USER_ADMIN_BEGIN = "UPDATE_USER_ADMIN_BEGIN";
export const UPDATE_USER_ADMIN_SUCCESS = "UPDATE_USER_ADMIN_SUCCESS";
export const UPDATE_USER_ADMIN_ERROR = "UPDATE_USER_ADMIN_ERROR";

export const SET_EDIT_USER = "SET_EDIT_USER";

export const CLEAR_STATE = "CLEAR_STATE";
